services:
  provider-chat-app-backend:
    build:
      context: ../../backend
      dockerfile: src/main/docker/Dockerfile.jvm
    # depends_on:
    #   provider:
    #     condition: 'service_healthy'
    #   provider-connector:
    #     condition: 'service_healthy'
    ports:
      - "18080:8080"
    environment:
      "chat-app.base-url-for-notification-callbacks": "http://provider-chat-app-backend:8080"
      "chat-app.edc.chat-app.edc.connector-endpoint": "http://provider:80/api/dsp"
      "chat-app.edc.management-api.url": "http://provider:80/api/management"
      "chat-app.edc.management-api.key": "SomeOtherApiKey"

  consumer-chat-app-backend:
    build:
      context: ../../backend
      dockerfile: src/main/docker/Dockerfile.jvm
    # depends_on:
    #   consumer:
    #     condition: 'service_healthy'
    #   consumer-connector:
    #     condition: 'service_healthy'
    ports:
      - "28080:8080"
    environment:
      "chat-app.base-url-for-notification-callbacks": "http://consumer-chat-app-backend:8080"
      "chat-app.edc.chat-app.edc.connector-endpoint": "http://consumer:80/api/dsp"
      "chat-app.edc.management-api.url": "http://consumer:80/api/management"
      "chat-app.edc.management-api.key": "SomeOtherApiKey"
