chat-app.base-url-for-notification-callbacks=http://localhost:8080
chat-app.edc.connector-endpoint=http://provider:11003/api/dsp
chat-app.edc.management-api.url=http://localhost:11000/api/management
chat-app.edc.management-api.key=SomeOtherApiKey
